CREATE TABLE HEART_DISEASE(
             AGE INT,
             SEX VARCHAR(50) NOT NULL,
             CHESTPAINTYPE VARCHAR(50) NOT NULL,
             RESTINGBP VARCHAR(50) NOT NULL,
             CHOLESTEROL VARCHAR(50) NOT NULL,
             FASTINGBS VARCHAR(50) NOT NULL,
             RESTINGECG VARCHAR(50) NOT NULL,
             MAXHR VARCHAR(50) NOT NULL,
             EXERCISEANGINA VARCHAR(50) NOT NULL,
             OLDPEAK VARCHAR(50) NOT NULL,
             ST_SLOPE VARCHAR(50) NOT NULL,
             HEARTDISEASE VARCHAR(50) NOT NULL,
             
);
